services:
  mcp-rfp-server:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./knowledge_base:/app/knowledge_base  # Only used when KNOWLEDGE_SOURCE=local
      - ./outputs:/app/outputs
      - ./chroma_data:/app/chroma_data
      - ./scripts:/app/scripts
    environment:
      # Core Configuration
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SERVER_NAME=mcp-rfp-server
      - LOG_LEVEL=INFO
      - DEBUG=false

      # Knowledge Source Configuration
      - KNOWLEDGE_SOURCE=${KNOWLEDGE_SOURCE:-local}

      # SharePoint Configuration (only used when KNOWLEDGE_SOURCE=sharepoint)
      - SHAREPOINT_TENANT_ID=${SHAREPOINT_TENANT_ID}
      - SHAREPOINT_CLIENT_ID=${SHAREPOINT_CLIENT_ID}
      - SHAREPOINT_CLIENT_SECRET=${SHAREPOINT_CLIENT_SECRET}
      - SHAREPOINT_SITE_URL=${SHAREPOINT_SITE_URL}
      - SHAREPOINT_FOLDER_PATH=${SHAREPOINT_FOLDER_PATH:-knowledge_base}

      # Local Knowledge Base (only used when KNOWLEDGE_SOURCE=local)
      - KNOWLEDGE_BASE_PATH=${KNOWLEDGE_BASE_PATH:-./knowledge_base}

      # Other Configuration
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-1.5-flash-latest}
      - CHROMA_DB_PATH=${CHROMA_DB_PATH:-./chroma_data}
      - OUTPUT_PATH=${OUTPUT_PATH:-./outputs}
      - SPACY_MODEL=${SPACY_MODEL:-en_core_web_sm}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-all-MiniLM-L6-v2}
      - MAX_DOCUMENT_SIZE_MB=${MAX_DOCUMENT_SIZE_MB:-50}
      - MAX_REQUIREMENTS_PER_DOCUMENT=${MAX_REQUIREMENTS_PER_DOCUMENT:-200}
      - DEFAULT_SEARCH_LIMIT=${DEFAULT_SEARCH_LIMIT:-5}
      - SIMILARITY_THRESHOLD=${SIMILARITY_THRESHOLD:-0.7}
      - CONFIDENCE_THRESHOLD=${CONFIDENCE_THRESHOLD:-0.6}
      - MCP_PROTOCOL_VERSION=${MCP_PROTOCOL_VERSION:-2024-11-05}
      - ENABLE_MCP_LOGGING=${ENABLE_MCP_LOGGING:-true}
    networks:
      - rfp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 8000)); s.close()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  rfp-network:
    driver: bridge